<!-- <div class="image-gallery">
    <ul class="product-images">
        <?php foreach ($block->getProductCollection() as $product): ?>
            <?php if ($product->getImage()): ?>
                <li><img width="200px" height="200px"  src="<?php echo $block->getProductImageUrl($product); ?>" alt="<?php echo $product->getName(); ?>"></li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
</div> -->
