<?php
$subCategoryUrls = $block->getSubCategoryUrls();

if($subCategoryUrls){ ?>
<style>
    .breadcrumbs{
        display:block;
    }
</style>
<?php
}else{ ?>
<style>
    .breadcrumbs{
        display:none;
    }
</style>
<?php
$crumbs = $block->getCrumbs(); 

if ($crumbs && is_array($crumbs)) : ?>
    <div class="container">
        <div class="custome-breadcrumbs">
            <ul class="custome-items">
                <?php
                foreach ($crumbs as $crumbName => $crumbInfo) : ?>
                    <li class="custome-item <?php echo $crumbName == 0 ? "home" : ""; ?>">
                        <?php if ($crumbInfo['link']) : ?>
                            <a href="<?= /* @escapeNotVerified */
                            $crumbInfo['link'] ?>" title="<?= $block->escapeHtml($crumbInfo['title']) ?>">
                                <?= $block->escapeHtml($crumbInfo['label']) ?>
                            </a>
                        <?php else: ?>
                            <strong><?= $block->escapeHtml($crumbInfo['label']) ?></strong>
                        <?php endif; ?>
                    </li>
                <?php
                endforeach; ?>
            </ul>
        </div>
    </div>
    <?php endif; 

}

?>
